[package]
name = "arrow-generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
arrow= "32.0.0"
clap = { version = "4.1.4", features = ["derive"] }
chrono = "0.4.2"